export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
// export const UPDATE_SORT = "UPDATE_SORT";
// export const UPDATE_CURRENT_SORT = "UPDATE_CURRENT_SORT"